language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t laviniapuscas/docker-react -f Dockerfile.dev .

script:
   doker run -e CI=true laviniapuscas/docker-react npm run test -- --coverage